### ISSUE TITLE
IP6 default constructor doesn't set 'extension_hdrs'

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#94]
_From [alexey.k...@gmail.com](https://code.google.com/u/111743032381162465908/) on March 31, 2011 05:37:35_

What steps will reproduce the problem? >>> import dpkt
>>> packet = dpkt.ip6.IP6()
>>> str(packet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dpkt/ip6.py", line 83, in **str**
    return self.pack_hdr() + self.headers_str() + str(self.data)
  File "dpkt/ip6.py", line 66, in headers_str
    if not self.extension_hdrs[hdr] is None:
AttributeError: 'IP6' object has no attribute 'extension_hdrs'
>>> What is the expected output? What do you see instead? This is expected output:
>>> import dpkt
>>> packet = dpkt.ip6.IP6()
>>> str(packet)
'`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' What version of the product are you using? On what operating system? First line of ip6.py:
# $Id: ip6.py 58 2010-03-06 00:06:14Z dugsong $ Please provide any additional information below. 'Expected output' above was produced with this workaround:

$ diff -u ip6_original.py ip6.py
--- ip6.py  2010-03-06 00:06:21.000000000 +0300
+++ ip6.py  2011-03-31 13:29:47.009915074 +0300
@@ -62,10 +62,10 @@
         """

```
     header_str = ""
```

\-        
-        for hdr in ext_hdrs:
-            if not self.extension_hdrs[hdr] is None:
-                header_str += str(self.extension_hdrs[hdr])
-        if getattr(self, 'extension_hdrs', None):
-            for hdr in ext_hdrs:
-                if not self.extension_hdrs[hdr] is None:
-                    header_str += str(self.extension_hdrs[hdr])
       return header_str

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=67_

**Comment by kbandla** [comment]
_From [jarethdi...@gmail.com](https://code.google.com/u/104418185413281640521/) on May 02, 2013 04:53:03_

I too am seeing the same problem, this fix seems to fix the problem.

When will this be fixed in the main release?

**Comment by sunhao2014** [comment]
The issue still exists.

When the user builds an empty IPv6 packet and output it as string, he may write the statement below.

``` python
packet = dpkt.ip6.IP6()
print str(packet)
```

Then we'll get the following exception.
``` python
Traceback (most recent call last):
  File "E:\dpkt_laptop\hao_test\issue94.py", line 4, in <module>
    str(packet)
  File "F:\Python27\lib\site-packages\dpkt-1.8.6.2-py2.7.egg\dpkt\ip6.py", line 113, in __str__
    if (self.p == 6 or self.p == 17 or self.p == 58) and not self.data.sum:
AttributeError: 'IP6' object has no attribute 'p'
```

This is because we didn't call `unpack` method if we use the default constructor of `ip6.py`. Therefore `IP6` object won't have the attribute of `p` and `extension_hdrs`. However definitely in `str()` we'll use the two attributes, please check the following code of `str()`.

``` python
def __str__(self):
        if (self.p == 6 or self.p == 17 or self.p == 58) and not self.data.sum:
            # XXX - set TCP, UDP, and ICMPv6 checksums
            p = str(self.data)
            s = dpkt.struct.pack('>16s16sxBH', self.src, self.dst, self.nxt, len(p))
            s = dpkt.in_cksum_add(0, s)
            s = dpkt.in_cksum_add(s, p)
            try:
                self.data.sum = dpkt.in_cksum_done(s)
            except AttributeError:
                pass
        return self.pack_hdr() + self.headers_str() + str(self.data)
```

Up to now, the issue should be clear. Thus the question is, is the usage of `packet = dpkt.ip6.IP6()` valid? If so, we need to update the constructor or `str` to fix this bug.

**Comment by obormot** [comment]
cleaning up old issues
no longer crashes the IP6() class
tested in both python 2 and 3:
```
>>> import dpkt
>>> str(dpkt.ip6.IP6())
'`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
